### ISSUE TITLE
Connedcted, but buttons eco, standard, turbo do nothing

### ISSUE THREAD

**Issue by Verguldebarman** [subparpedestrian/cphw-android#1]
First of all, thanks for your work!!

I tried both web & android and unfortunately, I cannot get it working. For Web, I've posted a [separate issue](https://github.com/subparpedestrian/cphw-web/issues/1) on your git. I'm sharing below my issue with the Android version.

What I have done and what works:

1. I have downloaded the code from github
2. build the APK with Android Studio
3. installed the app on my Android
4. app starts with status: disconnected and all buttons
5. when I click [connect] my CW is found and connected (all LEDs stop blinking and show a solid 5 LEDs  always on)
6. when I start riding the LEDs go off one at a time

and now the issue:

- I don't think the buttons eco, standard, turbo do anything, as I see nothing happening
- also the ride is not assisted by my CW

Troubleshooting:

- none I can think of

Any clue?

**Comment by subparpedestrian** [comment]
I have heard others say the mode changes do not work for them.  I am unsure why.  Your LEDs powering off sounds like there might be another issue here like the battery is no good.  Did you ride it successfully recently?

I put more effort now into the web app because it is easier to deploy and can act like a native app via PWA (chrome on android should give you the option to install it either with a pop up or in the chrome menu.

**Comment by Verguldebarman** [comment]
Thx, I will focus on web for now and follow the Android app for progress. This issue can be closed.
